회원(비회원 포함)들을 위한 질문 게시판
hansung-pocs/blog-android pull request #161
Opened 2022-08-13 06:38 UTC by ois0886

#152 

## Merge 전 체크리스트

- [ ] 코딩 컨벤션을 지켰는가?
- [ ] Action에서 진행하는 테스트를 모두 통과했는가?
- [ ] 수정 사항을 검증할 테스트를 추가하였는가?
- [ ] 리뷰를 받았는가?

2022-08-13 07:49 UTC, jja08111 requested changes
![image](https://user-images.githubusercontent.com/57604817/184474527-b30f3377-2a49-44c5-aff0-f1ee9e03f34d.png)
여기 탭에는 "질문답변"이라고 하는게 좋겠네요.

그리고 "질문하기"는 띄어쓰기 없이 하도록 해요.

2022-08-14 06:21 UTC, jja08111 requested changes
LGTM. 질문답변 구조가 아예 일반 글이랑 동일하게 진행되고 있나요? 궁금하네요.

2022-08-14 06:21 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/home/question/QuestionFragment.kt
> +        val intent = PostCreateActivity.getIntent(requireContext(), PostCategory.MEMORY)
TODO가 필요해보입니다.
```suggestion
       // TODO: 아래는 임시로 전달하는 enum임. 추후 질문 타입이 생기면 수정필요
        val intent = PostCreateActivity.getIntent(requireContext(), PostCategory.MEMORY)
```

2022-08-14 06:21 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
> +    private suspend fun savePost(): Result<Unit> { // TODO : 비회원 포스트 -> username : (비회원)
어떤 TODO인가요?

2022-08-14 06:21 UTC, jja08111 commented on presentation/src/main/res/menu/menu_bottom_navigation.xml
> +        />
코드 정렬해주세요

2022-08-14 07:57 UTC, ois0886 commented on presentation/src/main/java/com/pocs/presentation/view/home/question/QuestionFragment.kt
> +        val intent = PostCreateActivity.getIntent(requireContext(), PostCategory.MEMORY)
그 부분에서는 개인적으로 사실 고민이 많습니다. 단순 글을 작성하고 댓글 기능이 추가되었을 때, 댓글로만 답변을 주고받을지( 만약 이렇다면 PostCreate 부분을 조금 활용 가능합니다.) 아니면 따로 QuestionCreateActivity를 새롭게 만들어서 조금 더 비회원 사용자 편의에 맞는 기능들을 추가할지에 대해서 고민하고 있습니다. 또한 답글을 작성하는 면에서도 관리자가 새롭게 글을 작성하여 답글 : ~~~~ 이런 식으로 할지에 대해서 사용자 입장으로 생각을 하고 있고, 만약 비회원이 글을 작성한다면 글목록 화면에서 RecyclerView에 작성자 이름을 비회원 혹은 비회원 익명 어떤 것을 할지 고민을 하고 있습니다.
우선은 민성님께서 수정해 주신 것처럼 TODO 아래에 코드는 임시로 넣었습니다

2022-08-14 07:58 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/home/question/QuestionFragment.kt
> +        val intent = PostCreateActivity.getIntent(requireContext(), PostCategory.MEMORY)
아하 저도 같은 생각을 했었네요. 그부분은 팀이랑 같이 이야기해보시면서 결정하시면 됩니다.

2022-08-14 08:06 UTC, ois0886 commented on presentation/src/main/java/com/pocs/presentation/view/post/create/PostCreateViewModel.kt
> +    private suspend fun savePost(): Result<Unit> { // TODO : 비회원 포스트 -> username : (비회원)
이상한 곳에 TODO를 두었습니다. 죄송합니다.

2022-08-14 08:08 UTC, jja08111 approved these changes

2022-08-14 08:22 UTC, merged