익명계정 생성 UI 수정
hansung-pocs/blog-android pull request #207
Opened 2022-08-25 12:58 UTC by ois0886

기존에  필요하지않았던 '필수' 라벨을 삭제하였고, 비밀번호 텍스트 박스에 비밀번호를 감추었습니다.
로그인페이지에 사용되었던 PasswordOutlineTextField를 재사용하였기에 로직에서는 큰 차이가 없습니다.
<img width="369" alt="스크린샷 2022-08-25 오후 9 56 06" src="https://user-images.githubusercontent.com/58154638/186670924-6381ea20-0e28-48e0-9d06-5c1c2479248b.png">

## Merge 전 체크리스트

- [X] 코딩 컨벤션을 지켰는가?
- [ ] Action에서 진행하는 테스트를 모두 통과했는가?
- [ ] 수정 사항을 검증할 테스트를 추가하였는가?
- [ ] 리뷰를 받았는가?

2022-08-25 13:46 UTC, jja08111 requested changes
![image](https://user-images.githubusercontent.com/57604817/186681281-c325843f-1b31-4c40-ba33-fea72a864141.png)

위와 같이 안내 문구를 추가하면 어떨까요? 이는 피그마에 만들어 두었어요.

2022-08-25 13:46 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
> +import androidx.compose.material.icons.filled.VisibilityOff
안쓰는 import와 변수가 존재하네요. 나중에 이를 자동으로 확인할 수 있도록 CI에 linter를 추가하는게 좋겠네요.

2022-08-25 13:58 UTC, ois0886 commented on presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
> +import androidx.compose.material.icons.filled.VisibilityOff
확인하였습니다.

2022-08-25 15:28 UTC, ois0886 commented on presentation/src/main/res/values/strings.xml
> +    <string name="anonymous_precautions">임시 계정은 조회할 수 있는 게시글에 제한이 있어요. \n또한 임시 계정으로는 질문 답변 게시글만 작성 가능해요.</string>
아 그렇네요. 문맥상 정보성 전달의 의미에 더 가깝기때문에 민성님 의견이 더 맞는 것 같습니다. 감사합니다.

2022-08-25 15:39 UTC, jja08111 requested changes

2022-08-25 15:39 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
> +                textAlign = TextAlign.Center
피그마와 똑같이 구현해야해요. 텍스트 정렬은 없어도 됩니다.
```suggestion

```

2022-08-26 09:18 UTC, jja08111 requested changes
지금 구현사항을 피그마와 비교해보면 아래와 같습니다.

|디자인 요구사항|구현된 모습|
|---|---|
|![image](https://user-images.githubusercontent.com/57604817/186872248-8349a7e2-bfb7-4aa5-b308-905d8d3d63c7.png)|![image](https://user-images.githubusercontent.com/57604817/186869928-7a4648f0-7be4-45f5-9ef1-c9ef16658fa2.png)|

차이점이 보이시나요? **텍스트 UI**를 구현할 때는 꼭 신경 써야 할 것이 있습니다.
- 폰트 사이즈
- 줄간격(lineHeight): 모바일 환경에서는 글을 읽는것이 대형 화면 보다 어려움이 큽니다. 따라서 적절한 줄간격을 통해 간격을 띄워주어야 합니다.

위의 사항은 단 번에 찾을 수 없고 여러 값들을 넣어보며 디자인 요구사항과 비교하며 찾아가야합니다. 제가 이전 리뷰에 올렸던 예제들은 참고사항으로 말씀드린 것이지 항상 정답이 아닙니다.

현재 구현된 모습을 보면 폰트가 작고, 줄간격이 좁으며, 문장안에 `\n`가 존재합니다.

```kotlin
 style = MaterialTheme.typography.bodyMedium.copy(
    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.5f),
    lineHeight = 24.sp
),
```

다음에는 디자인 요구사항과 꼼꼼히 비교하며 구현하실 수 있을거라 생각합니다.

타이포그래피 UI 참고사항: https://yozm.wishket.com/magazine/detail/1017/

2022-08-26 09:18 UTC, jja08111 commented on presentation/src/main/res/values/strings.xml
> +    <string name="anonymous_guideline">임시 계정은 조회할 수 있는 게시글에 제한이 있어요. \n또한 임시 계정으로는 질문 답변 게시글만 작성 가능해요.</string>
엔터키 제거하여 한 문장으로 보이는게 좋을것같아요
```suggestion
    <string name="anonymous_guideline">임시 계정은 조회할 수 있는 게시글에 제한이 있어요. 또한 임시 계정으로는 질문 답변 게시글만 작성 가능해요.</string>
```

2022-08-26 09:36 UTC, ois0886 commented on presentation/src/main/res/values/strings.xml
> +    <string name="anonymous_guideline">임시 계정은 조회할 수 있는 게시글에 제한이 있어요. \n또한 임시 계정으로는 질문 답변 게시글만 작성 가능해요.</string>
아... 제가 계속 디테일한 부분을 놓쳤네요.. 죄송합니다. 계속 컴포즈 프리뷰와 피그마로 비교하다보니 실제 앱을 구동 하였을 때와 프리뷰로 볼때에 차이를 놓쳤던 것 같습니다. 죄송합니다. 시정하겠습니다.

2022-08-26 10:10 UTC, jja08111 reviewed
conflict가 발생했네요 rebase가 필요해보입니다.

2022-08-26 10:10 UTC, jja08111 commented on presentation/src/main/java/com/pocs/presentation/view/user/anonymous/AnonymousCreateScreen.kt
> +                ),
줄간격이 아직 좁게 보이네요. 아래와 같이 추가해주면 됩니다.
```suggestion
                ),
                 lineHeight = 24.sp
```

2022-08-26 13:54 UTC, jja08111 approved these changes
![](https://media.giphy.com/media/8MM0W6DapfrtizC5b3/giphy.gif)

2022-08-26 13:55 UTC, merged